# gen_combat_identity.ps1 — derive SpeciesIdentity for all 1025 from the PokeAPI CSVs (tools/pokeapi/).
# Output: src/lib/combat_identity.ts (GENERATED — do not hand-edit; re-run after a CSV refresh).
# Pure data → no scraping, no network. Part of the Pokemon Identity Engine (docs/COMBAT_IDENTITY.md).
$ErrorActionPreference = "Stop"
[System.Threading.Thread]::CurrentThread.CurrentCulture = "en-US" # force '.' decimals in output
$root = Split-Path $PSScriptRoot -Parent
$csv  = Join-Path $PSScriptRoot "pokeapi"
$out  = Join-Path $root "src\lib\combat_identity.ts"
$MAX  = 1025

$types = @{}; Import-Csv (Join-Path $csv "types.csv") | ForEach-Object { $types[[int]$_.id] = $_.identifier }
$ptypes = @{}; Import-Csv (Join-Path $csv "pokemon_types.csv") | ForEach-Object {
  $pk=[int]$_.pokemon_id; if($pk -le $MAX){ if(-not $ptypes.ContainsKey($pk)){$ptypes[$pk]=@{}}; $ptypes[$pk][[int]$_.slot]=$types[[int]$_.type_id] }
}
$pstats=@{}; Import-Csv (Join-Path $csv "pokemon_stats.csv") | ForEach-Object {
  $pk=[int]$_.pokemon_id; if($pk -le $MAX){ if(-not $pstats.ContainsKey($pk)){$pstats[$pk]=@{}}; $pstats[$pk][[int]$_.stat_id]=[int]$_.base_stat }
}
$pmon=@{}; Import-Csv (Join-Path $csv "pokemon.csv") | ForEach-Object {
  $id=[int]$_.id; if($id -le $MAX -and $_.is_default -eq "1"){ $pmon[$id]=@{ height=[double]$_.height; weight=[double]$_.weight } }
}
$spec=@{}; Import-Csv (Join-Path $csv "pokemon_species.csv") | ForEach-Object {
  $id=[int]$_.id; if($id -le $MAX){ $spec[$id]=@{ from=$_.evolves_from_species_id; leg=($_.is_legendary -eq "1" -or $_.is_mythical -eq "1") } }
}
$flavor=@{}
# Concatenate ALL English entries per species — we only store derived tags, so more text = richer
# motif/temperament signal (e.g. Charizard's "seeks strong opponents" lives in a later entry).
Import-Csv (Join-Path $csv "pokemon_species_flavor_text.csv") | Where-Object { $_.language_id -eq "9" } | ForEach-Object {
  $sid=[int]$_.species_id; if($sid -le $MAX){ if(-not $flavor.ContainsKey($sid)){ $flavor[$sid]="" }; $flavor[$sid] += " " + $_.flavor_text }
}

function Get-Stage([int]$dex){
  $f=$spec[$dex].from
  if([string]::IsNullOrEmpty($f)){return 1}
  $f2=$spec[[int]$f].from
  if([string]::IsNullOrEmpty($f2)){return 2}
  return 3
}
function Clamp01($x){ if($x -lt 0){return 0}; if($x -gt 1){return 1}; return [math]::Round($x,3) }

$motifKW = [ordered]@{
  aerial   = "wing|flies|flying|soar|sky|flight|bird"
  infernal = "fire|flame|blaze|burn|heat|magma|lava|inferno"
  aquatic  = "water|sea|ocean|swim|river|aqua|tide"
  ghostly  = "ghost|shadow|spirit|haunt|lurk|grudge|curse"
  electric = "electric|thunder|lightning|spark|volt"
  toxic    = "poison|toxic|venom"
  psychic  = "psychic|mind|telekine|\besp\b"
  icy      = "ice|frost|snow|freezing|\bcold\b"
  heavy    = "heavy|huge|massive|enormous|weighs|giant"
  regal    = "majestic|ruler|\bking\b|deity|sacred|legend|guardian"
}
$tempKW = [ordered]@{
  challenger = "seeks.*strong|rival|battle|powerful opponent|\bproud\b|fierce|aggressive"
  protective = "protect|guard|defen|shield"
  loyal      = "gentle|kind|guides|helps|friendly|trusts|devoted|loving|affection"
  sleepy     = "sleep|lazy|doze|\bnap|drowsy|slumber"
  playful    = "\bplay|mischie|prank|curious|trick"
  aloof      = "solitary|alone|rarely seen|reclus|\bwary\b|silent"
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Auto-generated by tools/gen_combat_identity.ps1 from the PokeAPI CSVs in tools/pokeapi/.")
[void]$sb.AppendLine("// DO NOT hand-edit; re-run the script. Derived identity for the default-form Pokemon (<= $MAX).")
[void]$sb.AppendLine("// Per dex: [t1, t2, tempo, scale, power, bias, legendary(0|1), stage, motifs[], temperament[]]")
[void]$sb.AppendLine('export type IdentityTuple = [string, string, number, number, number, "phys" | "spec" | "bal", 0 | 1, 1 | 2 | 3, string[], string[]];')
[void]$sb.AppendLine("export const COMBAT_IDENTITY: Record<number, IdentityTuple> = {")

$count = 0
for($dex=1; $dex -le $MAX; $dex++){
  if(-not $pmon.ContainsKey($dex) -or -not $pstats.ContainsKey($dex) -or -not $ptypes.ContainsKey($dex)){ continue }
  $t1 = $ptypes[$dex][1]; $t2 = $ptypes[$dex][2]; if(-not $t2){ $t2 = "" }
  $atk=$pstats[$dex][2]; $spatk=$pstats[$dex][4]; $speed=$pstats[$dex][6]
  $tempo = Clamp01($speed/160.0)
  $kg = $pmon[$dex].weight/10.0; $m = $pmon[$dex].height/10.0
  $scale = Clamp01( ([math]::Log10($kg+1)/3.0 + $m/12.0)/2.0 )
  $power = Clamp01([math]::Max($atk,$spatk)/180.0)
  if($atk-$spatk -gt 15){ $bias="phys" } elseif($spatk-$atk -gt 15){ $bias="spec" } else { $bias="bal" }
  $leg = if($spec[$dex].leg){1}else{0}
  $stage = Get-Stage $dex
  $fx = ""; if($flavor.ContainsKey($dex)){ $fx = ($flavor[$dex] -replace "[\f\r\n]"," ").ToLower() }
  $motifs = New-Object System.Collections.Generic.List[string]
  if($t1){ [void]$motifs.Add($t1) }
  foreach($k in $motifKW.Keys){ if($fx -match $motifKW[$k] -and -not $motifs.Contains($k)){ [void]$motifs.Add($k) } }
  if($leg -eq 1 -and -not $motifs.Contains("regal")){ [void]$motifs.Add("regal") }
  $temps = New-Object System.Collections.Generic.List[string]
  foreach($k in $tempKW.Keys){ if($fx -match $tempKW[$k]){ [void]$temps.Add($k) } }
  if($temps.Count -eq 0){ [void]$temps.Add("calm") }
  $mj = ($motifs | ForEach-Object { '"' + $_ + '"' }) -join ","
  $tj = ($temps  | ForEach-Object { '"' + $_ + '"' }) -join ","
  [void]$sb.AppendLine("$($dex):[""$t1"",""$t2"",$tempo,$scale,$power,""$bias"",$leg,$stage,[$mj],[$tj]],")
  $count++
}
[void]$sb.AppendLine("};")
[System.IO.File]::WriteAllText($out, $sb.ToString())
"wrote $out  ($count species)"